
const NODEL_FAILED = 'NODEL_FAILED';
const NOT_INCLUDED = 'NOT_INCLUDED';
const NOT_MATCHING = 'NOT_MATCHING'; 
const NOT_AUTHENTICATED = 'NOT_AUTHENTICATED';
const WRONG_AUTH_TYPE = 'WRONG_AUTH_TYPE';
const OK = 'OK';

module.exports = { NODEL_FAILED, NOT_INCLUDED, NOT_MATCHING, NOT_AUTHENTICATED, OK }
