---
services:
  aggregator:
    image: aggregator:latest
    restart: always
    ports:
      - 3000:3000
    environment:
      - MONGODB_URI={{ aggregator_mongodb_uri }}
      - PORT=3000
      - ALPHABILL_NETWORK_ID=1
      - ALPHABILL_TOKEN_PARTITION_ID=102
      - ALPHABILL_TOKEN_PARTITION_URL=https://putp.mainnet.alphabill.org/rpc
      - ALPHABILL_PRIVATE_KEY={{ aggregator_private_key }}
      - ENABLE_HIGH_AVAILABILITY=false
      - INITIAL_BLOCK_HASH={{ aggregator_initial_block_hash }}
      - LOG_FORMAT=json
      - LOG_TO_FILE=false
    # - LOG_LEVEL=info
    logging:
      driver: fluentd
      options:
        fluentd-address: "127.0.0.1:24224"
        tag: "aggregator"
        mode: "non-blocking"

volumes:
  mongodb-data:
