name: Build Aggregator client Docker image

on:
  push:
    branches:
      - main
      - devnet

jobs:
  build:
    outputs:
      image_digest: ${{ steps.build-and-push.outputs.digest }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        id: build-and-push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository }}:${{ github.sha }}

      - name: Print image digest
        run: |
         echo "Image digest is: ${{ steps.build-and-push.outputs.digest }}"

  call-deploy:
    needs: build
    uses: ./.github/workflows/deploy.yml
    with:
      aggregator_tag: ${{ needs.build.outputs.image_digest }}
      environment: devnet
