name: Deploy

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment'
        required: true
        type: choice
        options:
          - devnet
          - mainnet_test
          - mainnet
        default: 'devnet'
      aggregator_tag:
        description: 'Docker image is tagged with git commit id. Can be resolved from branch or tag.'
        required: true
        type: string
        default: 'origin/main'
  workflow_call:
    inputs:
      environment:
        description: 'Environment'
        required: true
        type: string
      aggregator_tag:
        description: 'Docker image hash'
        required: true
        type: string
    secrets:
      SSH_PRIVATE_KEY:
        required: true
      ANSIBLE_VAULT_PASSWORD:
        required: true

jobs:
  deploy:
    name: Deploy Aggregator to ${{ inputs.environment }}
    runs-on: ubuntu-latest
    environment:
      name: "${{ inputs.environment }}"
    steps:

      - name: Check out repository code
        uses: actions/checkout@v4 # Always use the latest major version
        with:
          # Fetch all history for all tags and branches
          fetch-depth: 0 # Important to get refs of other branches

      - name: Process input
        id: process_inputs
        run: |
          echo "Triggered by: ${{ github.event_name }}"
          raw_input="${{ inputs.aggregator_tag }}"
          trimmed_input=$(echo "$raw_input" | sed 's/^[[:space:]]*//;s/[[:space:]]*$//')
          COMMIT_ID=$(git rev-parse "${trimmed_input}")
          ENVIRONMENT="${{ inputs.environment }}"

          # input parameters
          echo "commit_id=${COMMIT_ID}"
          echo "commit_id=${COMMIT_ID}" >> $GITHUB_OUTPUT
          echo "environment=${ENVIRONMENT}"
          echo "environment=${ENVIRONMENT}" >> $GITHUB_OUTPUT

          # check if docker image exists
          docker manifest inspect "ghcr.io/unicitynetwork/aggregators_net:${COMMIT_ID}"

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x' # Use a specific version like '3.9' or '3.11' if needed

      - name: Install Ansible
        run: |
          python -m pip install --upgrade pip
          pip install ansible # Or specify a version like ansible==7.4.0

      - name: Configure SSH Key
        uses: webfactory/ssh-agent@v0.9.1
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Configure ssh
        run: |
          mkdir -p ~/.ssh

          ssh-keyscan "jump-1.devnet.alphabill.org" >> ~/.ssh/known_hosts
          ssh-keyscan "jump-1.mainnet.alphabill.org" >> ~/.ssh/known_hosts

          cat > ~/.ssh/config <<- EOF
          Host devjump
            HostName jump-1.devnet.alphabill.org
            User alpha

          Host mainjump
            HostName jump-1.mainnet.alphabill.org
            User alpha

          Host *.devnet-v2.alphabill.internal
            ProxyJump devjump
            StrictHostKeyChecking accept-new
            User alpha

          Host *.mainnet-v3.alphabill.internal
            ProxyJump mainjump
            StrictHostKeyChecking accept-new
            User alpha
          EOF
          cat ~/.ssh/config

      - name: Run Ansible Playbook
        working-directory: ./ansible
        env:
          ANSIBLE_VAULT_PASSWORD: ${{ secrets.ANSIBLE_VAULT_PASSWORD }}
          ANSIBLE_VAULT_PASSWORD_FILE: .vault_pass
        run: |
          echo "$ANSIBLE_VAULT_PASSWORD" > .vault_pass
          chmod 600 .vault_pass

          ansible-playbook aggregator.yml \
          -e "env=${{ steps.process_inputs.outputs.environment }}" \
          -e "aggregator_tag=${{ steps.process_inputs.outputs.commit_id }}"

