name: Run Tests with Docker

on:
  push:
    branches: [ main, fix-github-action ]

jobs:
  test:
    runs-on: ubuntu-latest

    permissions:
      contents: write # needed to write Alphabill genesis files to disk

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.14.0'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm run test
